[tool.black]
line-length = 90
target-version = ["py312"]

[flake8]
max-line-length = 90

[tool.isort]
profile = "black"
line_length = 90
multi_line_output = 3
skip_gitignore = true
src_paths = ["./src"]
